In [1]:
!pip install -q transformers datasets evaluate accelerate

import torch, pandas as pd, numpy as np
from datasets import load_dataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          TrainingArguments, Trainer, DataCollatorWithPadding)
import evaluate
from sklearn.metrics import classification_report

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.8 MB/s eta 0:00:00

Instalo librerías necesarias

#Carga

In [2]:
from huggingface_hub import login
from datasets import load_dataset
import pandas as pd


login(token="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")

dataset_name = "hugobecerra/DATASET3.0"


splits = {
    "train": f"hf://datasets/{dataset_name}/train.csv",
    "dev":   f"hf://datasets/{dataset_name}/dev.csv",
    "test":  f"hf://datasets/{dataset_name}/test_1.csv"
}

# Función genérica para cargar cada split y convertirlo en DataFrame
def load_split(path, name):
    ds = load_dataset("csv", data_files={name: path}, delimiter="\t")[name]
    df = pd.DataFrame(ds)
    df.dropna(subset=["text", "label"], inplace=True)
    df["text"] = df["text"].astype(str)
    df["label"] = df["label"].astype(int)
    return df

train_df = load_split(splits["train"], "train")
dev_df   = load_split(splits["dev"], "dev")
test_df  = load_split(splits["test"], "test")

# Combino train y dev como en la competición original
train_full_df = pd.concat([train_df, dev_df], ignore_index=True)

print(f"TRAIN+DEV → {len(train_full_df)} frases ({train_full_df['label'].sum()} relevantes)")
print(f"TEST → {len(test_df)} frases ({test_df['label'].sum()} relevantes)")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

train.csv:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

dev.csv:   0%|          | 0.00/231k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

test_1.csv:   0%|          | 0.00/92.5k [00:00<?, ?B/s]

Generating test split: 0 examples [00:00, ? examples/s]

TRAIN+DEV → 10648 frases (2283 relevantes)
TEST → 618 frases (90 relevantes)

#Tokenización

In [3]:
from transformers import AutoTokenizer, DataCollatorWithPadding

model_checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

def tokenize_function(batch):
    return tokenizer(batch["text"], truncation=True, padding=False, max_length=128)

# Tokenizo cada split a partir de los DataFrames
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_full_df).map(tokenize_function, batched=True)
dev_dataset   = Dataset.from_pandas(dev_df).map(tokenize_function, batched=True)
test_dataset  = Dataset.from_pandas(test_df).map(tokenize_function, batched=True)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Map:   0%|          | 0/10648 [00:00<?, ? examples/s]

Map:   0%|          | 0/1213 [00:00<?, ? examples/s]

Map:   0%|          | 0/618 [00:00<?, ? examples/s]

#Métricas de evaluación

In [4]:
import evaluate
import numpy as np

metric_f1 = evaluate.load("f1")
metric_acc = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    f1_minor = metric_f1.compute(predictions=preds, references=labels, pos_label=1)["f1"]
    macro_f1 = metric_f1.compute(predictions=preds, references=labels, average="macro")["f1"]
    acc = metric_acc.compute(predictions=preds, references=labels)["accuracy"]
    return {"F1_minor": f1_minor, "macro_F1": macro_f1, "accuracy": acc}

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

#Entrenamiento con fine-tuning bert base

In [6]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=2)

args = TrainingArguments(
    output_dir="./results_bert",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=4,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="F1_minor",
    greater_is_better=True,
    logging_steps=100,
    report_to="none"                  # evita que intente conectar con wandb
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-2306560150.py:21: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

TrainOutput(global_step=2664, training_loss=0.1993815103271702, metrics={'train_runtime': 625.6163, 'train_samples_per_second': 68.08, 'train_steps_per_second': 4.258, 'total_flos': 1533842897213280.0, 'train_loss': 0.1993815103271702, 'epoch': 4.0})

#Evaluación

In [7]:

from sklearn.metrics import classification_report, f1_score, accuracy_score

preds = trainer.predict(test_dataset)
y_true = preds.label_ids
y_pred = np.argmax(preds.predictions, axis=1)

print("\n=== REPORT ===")
print(classification_report(y_true, y_pred, digits=4, target_names=["No relevante", "Relevante"]))

print(f"🎯 F1 clase relevante: {f1_score(y_true, y_pred, pos_label=1):.4f}")
print(f"📈 Macro F1: {f1_score(y_true, y_pred, average='macro'):.4f}, Accuracy: {accuracy_score(y_true, y_pred):.4f}")

=== REPORT ===
              precision    recall  f1-score   support

No relevante     0.9624    0.7746    0.8583       528
   Relevante     0.3834    0.8222    0.5230        90

    accuracy                         0.7816       618
   macro avg     0.6729    0.7984    0.6907       618
weighted avg     0.8780    0.7816    0.8095       618

🎯 F1 clase relevante: 0.5230
📈 Macro F1: 0.6907, Accuracy: 0.7816

#DATA AUGMENTATION -- BACK TRANSLATION

In [9]:
!pip install -q transformers sentencepiece

from transformers import pipeline
import random
import pandas as pd

# Seleccionamos solo frases relevantes para aumentar
minority_df = train_full_df[train_full_df["label"] == 1].copy()

# Pipelines para traducción: inglés → francés → inglés
translator_en_fr = pipeline("translation", model="Helsinki-NLP/opus-mt-en-fr")
translator_fr_en = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en")

augmented_texts = []
for i, text in enumerate(minority_df["text"].sample(300, random_state=42)):  # 300 ejemplos como muestra
    try:
        fr_text = translator_en_fr(text)[0]["translation_text"]
        back_text = translator_fr_en(fr_text)[0]["translation_text"]
        augmented_texts.append(back_text)
    except Exception as e:
        continue

# Creamos DataFrame con las frases aumentadas
augmented_df = pd.DataFrame({
    "text": augmented_texts,
    "label": [1] * len(augmented_texts)
})

# Combinamos con el conjunto de entrenamiento original
train_aug_df = pd.concat([train_full_df, augmented_df], ignore_index=True)
print(f"🔄 Train aumentado: {len(train_aug_df)} frases totales ({train_aug_df['label'].sum()} relevantes)")

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/301M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
Device set to use cuda:0

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/301M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

🔄 Train aumentado: 10948 frases totales (2583 relevantes)

#NUEVA TOKENIZACIÓN

In [10]:
from datasets import Dataset

train_aug_dataset = Dataset.from_pandas(train_aug_df).map(tokenize_function, batched=True)

Map:   0%|          | 0/10948 [00:00<?, ? examples/s]

#NUEVO ENTRENAMIENTO

In [12]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

model_aug = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=2)

args_aug = TrainingArguments(
    output_dir="./results_bert_aug",
    eval_strategy="epoch",            # ✅ cambiado desde 'evaluation_strategy'
    save_strategy="epoch",            # mantiene checkpoints por época
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=4,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="F1_minor",
    greater_is_better=True,
    logging_steps=100,
    report_to="none"                  # desactiva Weights & Biases
)

trainer_aug = Trainer(
    model=model_aug,
    args=args_aug,
    train_dataset=train_aug_dataset,
    eval_dataset=dev_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer_aug.train()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-4208997364.py:21: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer_aug = Trainer(

TrainOutput(global_step=2740, training_loss=0.19353428722298058, metrics={'train_runtime': 656.4855, 'train_samples_per_second': 66.707, 'train_steps_per_second': 4.174, 'total_flos': 1575580943924880.0, 'train_loss': 0.19353428722298058, 'epoch': 4.0})

#NUEVA EVALUACIÓN

In [13]:
preds_aug = trainer_aug.predict(test_dataset)
y_true = preds_aug.label_ids
y_pred = np.argmax(preds_aug.predictions, axis=1)

print("\n=== REPORT (DATA AUGMENTATION) ===")
print(classification_report(y_true, y_pred, digits=4, target_names=["No relevante", "Relevante"]))

print(f"🎯 F1 clase relevante: {f1_score(y_true, y_pred, pos_label=1):.4f}")
print(f"📈 Macro F1: {f1_score(y_true, y_pred, average='macro'):.4f}, Accuracy: {accuracy_score(y_true, y_pred):.4f}")

=== REPORT (DATA AUGMENTATION) ===
              precision    recall  f1-score   support

No relevante     0.9630    0.7898    0.8678       528
   Relevante     0.4000    0.8222    0.5382        90

    accuracy                         0.7945       618
   macro avg     0.6815    0.8060    0.7030       618
weighted avg     0.8811    0.7945    0.8198       618

🎯 F1 clase relevante: 0.5382
📈 Macro F1: 0.7030, Accuracy: 0.7945