# BERT + Back-Translation — Protocolo corregido

Replica el experimento de `BERT_BERT_BACKSTRANSLATION.ipynb` corrigiendo dos problemas:

1. **Eval contaminado**: el original usaba `eval_dataset=dev_dataset` mientras dev formaba parte del corpus de entrenamiento. Aquí se evalúa directamente sobre **test**, igual que el resto de Transformers en `Fine_Tuning_multimodelo.ipynb`.
2. **Hiperparámetros inconsistentes**: el original usaba lr=2e-5, 4 épocas, batch=16. Aquí se usa **lr=5e-5, 3 épocas, batch=8**, el mismo protocolo que RoBERTa, DeBERTa, CTI-BERT, SecureBERT 2.0 y SecBERT.

Lo que **no cambia**: fusión train+dev (10.648 frases) como corpus de entrenamiento, back-translation EN→FR→EN con 300 muestras y semilla 42.

In [2]:
!pip install -q transformers datasets evaluate torch accelerate sentencepiece

import torch, pandas as pd, numpy as np
from datasets import load_dataset, Dataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          Trainer, TrainingArguments, DataCollatorWithPadding)
from sklearn.metrics import (classification_report, f1_score,
                              accuracy_score, precision_recall_fscore_support)
from huggingface_hub import login

login(token="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")

## 1. Carga de datos

In [3]:
dataset_name = "hugobecerra/DATASET3.0"
splits = {
    "train": f"hf://datasets/{dataset_name}/train.csv",
    "dev":   f"hf://datasets/{dataset_name}/dev.csv",
    "test":  f"hf://datasets/{dataset_name}/test_1.csv"
}

def load_split(path, name):
    ds = load_dataset("csv", data_files={name: path}, delimiter="\t")[name]
    df = pd.DataFrame(ds)
    df.dropna(subset=["text", "label"], inplace=True)
    df["text"] = df["text"].astype(str)
    df["label"] = df["label"].astype(int)
    return df

train_df = pd.concat([
    load_split(splits["train"], "train"),
    load_split(splits["dev"],   "dev")
], ignore_index=True)
test_df = load_split(splits["test"], "test")

print(f"TRAIN+DEV : {len(train_df)} frases ({train_df['label'].sum()} relevantes)")
print(f"TEST      : {len(test_df)} frases ({test_df['label'].sum()} relevantes)")

train.csv:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

dev.csv:   0%|          | 0.00/231k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

test_1.csv:   0%|          | 0.00/92.5k [00:00<?, ?B/s]

Generating test split: 0 examples [00:00, ? examples/s]

TRAIN+DEV : 10648 frases (2283 relevantes)
TEST      : 618 frases (90 relevantes)

## 2. Tokenización y métricas

In [4]:
model_checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

def tokenize_function(batch):
    return tokenizer(batch["text"], padding=True, truncation=True, max_length=128)

train_dataset = Dataset.from_pandas(train_df).map(tokenize_function, batched=True)
test_dataset  = Dataset.from_pandas(test_df).map(tokenize_function, batched=True)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Map:   0%|          | 0/10648 [00:00<?, ? examples/s]

Map:   0%|          | 0/618 [00:00<?, ? examples/s]

In [5]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary"
    )
    macro_f1 = precision_recall_fscore_support(labels, preds, average="macro")[2]
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "f1": f1, "precision": precision,
            "recall": recall, "macro_f1": macro_f1}

## 3. BERT sin aumento de datos

Entrenamiento sobre train+dev (10.648). Evaluación sobre test.
Sin selección de checkpoint: el modelo guardado es el estado final.

In [8]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=2
)

args = TrainingArguments(
    output_dir="./results_bert",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,      # train + dev
    processing_class=tokenizer,       # sustituye a tokenizer=
    compute_metrics=compute_metrics,
)

trainer.train()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=3993, training_loss=0.31581725997791055, metrics={'train_runtime': 863.7673, 'train_samples_per_second': 36.982, 'train_steps_per_second': 4.623, 'total_flos': 2101204888104960.0, 'train_loss': 0.31581725997791055, 'epoch': 3.0})

In [9]:
preds  = trainer.predict(test_dataset)
y_true = preds.label_ids
y_pred = np.argmax(preds.predictions, axis=1)

print("\n=== BERT sin aumento ===")
print(classification_report(y_true, y_pred, digits=4,
                             target_names=["No relevante", "Relevante"]))
print(f"F1 clase relevante : {f1_score(y_true, y_pred, pos_label=1):.4f}")
print(f"Macro F1           : {f1_score(y_true, y_pred, average='macro'):.4f}")
print(f"Accuracy           : {accuracy_score(y_true, y_pred):.4f}")

=== BERT sin aumento ===
              precision    recall  f1-score   support

No relevante     0.9561    0.7841    0.8616       528
   Relevante     0.3838    0.7889    0.5164        90

    accuracy                         0.7848       618
   macro avg     0.6700    0.7865    0.6890       618
weighted avg     0.8728    0.7848    0.8113       618

F1 clase relevante : 0.5164
Macro F1           : 0.6890
Accuracy           : 0.7848

## 4. Back-translation: generación de frases aumentadas

Sobre las relevantes de train+dev (2.283 frases). Ruta EN→FR→EN, semilla 42, 300 muestras.

In [11]:
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

device = "cuda" if torch.cuda.is_available() else "cpu"

# Frases relevantes del corpus actual: train+dev
minority_df = train_df[train_df["label"] == 1].copy()
print(f"Frases relevantes en train+dev: {len(minority_df)}")

# Modelos de traducción
en_fr_name = "Helsinki-NLP/opus-mt-en-fr"
fr_en_name = "Helsinki-NLP/opus-mt-fr-en"

tok_en_fr = AutoTokenizer.from_pretrained(en_fr_name)
mod_en_fr = AutoModelForSeq2SeqLM.from_pretrained(en_fr_name).to(device)

tok_fr_en = AutoTokenizer.from_pretrained(fr_en_name)
mod_fr_en = AutoModelForSeq2SeqLM.from_pretrained(fr_en_name).to(device)

def translate_batch(texts, tokenizer, model, batch_size=16, max_length=128):
    outputs = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]

        inputs = tokenizer(
            batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length
        ).to(device)

        with torch.no_grad():
            generated = model.generate(
                **inputs,
                max_length=max_length,
                num_beams=4
            )

        decoded = tokenizer.batch_decode(
            generated,
            skip_special_tokens=True
        )

        outputs.extend(decoded)

    return outputs

# Muestra fija de 300 frases relevantes de train+dev
sample_texts = (
    minority_df["text"]
    .sample(300, random_state=42)
    .astype(str)
    .tolist()
)

# Back-translation: EN -> FR -> EN
fr_texts = translate_batch(sample_texts, tok_en_fr, mod_en_fr)
back_texts = translate_batch(fr_texts, tok_fr_en, mod_fr_en)

augmented_df = pd.DataFrame({
    "text": back_texts,
    "label": [1] * len(back_texts)
})

train_aug_df = pd.concat([train_df, augmented_df], ignore_index=True)

print(f"Frases aumentadas generadas: {len(augmented_df)}")
print(f"Train aumentado: {len(train_aug_df)} frases ({train_aug_df['label'].sum()} relevantes)")

Frases relevantes en train+dev: 2283

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.34M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/301M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.34M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/301M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/256 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

Frases aumentadas generadas: 300
Train aumentado: 10948 frases (2583 relevantes)

In [12]:
train_aug_dataset = Dataset.from_pandas(train_aug_df).map(tokenize_function, batched=True)

Map:   0%|          | 0/10948 [00:00<?, ? examples/s]

## 5. BERT con back-translation

Mismo protocolo. Solo cambia `train_dataset`.

In [14]:
model_aug = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=2
)

args_aug = TrainingArguments(
    output_dir="./results_bert_aug",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    report_to="none"
)

trainer_aug = Trainer(
    model=model_aug,
    args=args_aug,
    train_dataset=train_aug_dataset,      # train+dev + frases aumentadas
    processing_class=tokenizer,           # sustituye a tokenizer=
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer_aug.train()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=4107, training_loss=0.2576553422748128, metrics={'train_runtime': 1096.5159, 'train_samples_per_second': 29.953, 'train_steps_per_second': 3.745, 'total_flos': 2160404875560960.0, 'train_loss': 0.2576553422748128, 'epoch': 3.0})

In [15]:
preds_aug  = trainer_aug.predict(test_dataset)
y_true_aug = preds_aug.label_ids
y_pred_aug = np.argmax(preds_aug.predictions, axis=1)

print("\n=== BERT + back-translation ===")
print(classification_report(y_true_aug, y_pred_aug, digits=4,
                             target_names=["No relevante", "Relevante"]))
print(f"F1 clase relevante : {f1_score(y_true_aug, y_pred_aug, pos_label=1):.4f}")
print(f"Macro F1           : {f1_score(y_true_aug, y_pred_aug, average='macro'):.4f}")
print(f"Accuracy           : {accuracy_score(y_true_aug, y_pred_aug):.4f}")

=== BERT + back-translation ===
              precision    recall  f1-score   support

No relevante     0.9560    0.7822    0.8604       528
   Relevante     0.3817    0.7889    0.5145        90

    accuracy                         0.7832       618
   macro avg     0.6689    0.7855    0.6875       618
weighted avg     0.8724    0.7832    0.8100       618

F1 clase relevante : 0.5145
Macro F1           : 0.6875
Accuracy           : 0.7832

## 6. Resumen

In [17]:
f1_bert     = f1_score(y_true,     y_pred,     pos_label=1)
f1_bert_aug = f1_score(y_true_aug, y_pred_aug, pos_label=1)

print("="*60)
print(f"{'Modelo':<40} {'F1 relevante':>12}")
print("-"*60)
print(f"{'BERT (train+dev, estado final)':<40} {f1_bert:>12.4f}")
print(f"{'BERT + BT (train+dev, estado final)':<40} {f1_bert_aug:>12.4f}")
print("="*60)
print()
print("Referencia notebook original (protocolo incorrecto):")
print(f"  BERT          (train+dev, eval dev contaminado): 0.5230")
print(f"  BERT + BT     (train+dev, eval dev contaminado): 0.5382")

============================================================
Modelo                                   F1 relevante
------------------------------------------------------------
BERT (train+dev, estado final)                 0.5164
BERT + BT (train+dev, estado final)            0.5145
============================================================

Referencia notebook original (protocolo incorrecto):
  BERT          (train+dev, eval dev contaminado): 0.5230
  BERT + BT     (train+dev, eval dev contaminado): 0.5382