In [4]:
import numpy as np
from collections import Counter

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, f1_score, accuracy_score

In [2]:
# LOGIN
login(token="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")

dataset_name = "hugobecerra/DATASET3.0"

splits = {
    "train": f"hf://datasets/{dataset_name}/train.csv",
    "dev":   f"hf://datasets/{dataset_name}/dev.csv",
    "test":  f"hf://datasets/{dataset_name}/test_1.csv"
}

def load_split(path, name):
    ds = load_dataset("csv", data_files={name: path}, delimiter="\t")[name]
    df = pd.DataFrame(ds)
    df.dropna(subset=["text", "label"], inplace=True)
    df["text"] = df["text"].astype(str)
    df["label"] = df["label"].astype(int)
    return df

train_df = load_split(splits["train"], "train")
dev_df   = load_split(splits["dev"], "dev")
test_df  = load_split(splits["test"], "test")

train_full_df = pd.concat([train_df, dev_df], ignore_index=True)

print("TRAIN+DEV →", train_full_df.shape)
print("TEST →", test_df.shape)

train_full_df.head()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

train.csv:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

dev.csv:   0%|          | 0.00/231k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

test_1.csv:   0%|          | 0.00/92.5k [00:00<?, ?B/s]

Generating test split: 0 examples [00:00, ? examples/s]

TRAIN+DEV → (10648, 3)
TEST → (618, 3)

,id,text,label
0,fireeye-operation-saffron-rose-1,We believe we 're seeing an evolution and deve...,0
1,fireeye-operation-saffron-rose-2,"In years past , Iranian actors primarily commi...",1
2,fireeye-operation-saffron-rose-3,"More recently , however , suspected Iranian ac...",1
3,fireeye-operation-saffron-rose-4,"In this report , we document the activities of...",0
4,fireeye-operation-saffron-rose-5,Members of this group have accounts on popular...,0

In [5]:
# X e y de entrenamiento (train + dev)
X_train = train_full_df["text"].values
y_train = train_full_df["label"].values

# X e y de test (test_1 "oficial")
X_test = test_df["text"].values
y_test = test_df["label"].values

print("Train:", Counter(y_train))
print("Test: ", Counter(y_test))

Train: Counter({np.int64(0): 8365, np.int64(1): 2283})
Test:  Counter({np.int64(0): 528, np.int64(1): 90})

In [6]:
from sklearn.metrics import make_scorer

pipe_svm = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        ngram_range=(1, 2),
        max_df=0.9,
        min_df=1
    )),
    ("svm", LinearSVC())
])

# Rejilla de hiperparámetros (ajustable)
param_grid = {
    "tfidf__ngram_range": [(1,1), (1,2)],
    "tfidf__max_df": [0.9, 1.0],
    "tfidf__min_df": [1, 2],
    "svm__C": [0.25, 0.5, 1.0, 2.0],
    "svm__class_weight": [None, "balanced"]
}

# Métrica: F1 de la clase relevante (1)
f1_relevant_scorer = make_scorer(f1_score, pos_label=1)

In [7]:
# --- Queremos que cada validación tenga la MISMA distribución que el test ---
test_counts = Counter(y_test)
n_val_pos = test_counts[1]   # p.ej. 90
n_val_neg = test_counts[0]   # p.ej. 528
val_size = n_val_pos + n_val_neg

print(f"Validación por fold: {n_val_pos} relevantes, {n_val_neg} no relevantes (total {val_size})")

# Índices por clase en el train_full
idx_pos = np.where(y_train == 1)[0]
idx_neg = np.where(y_train == 0)[0]

np.random.seed(42)
np.random.shuffle(idx_pos)
np.random.shuffle(idx_neg)

n_splits = 5  # número de folds

assert n_val_pos * n_splits <= len(idx_pos), "No hay suficientes positivos en train_full para estos folds"
assert n_val_neg * n_splits <= len(idx_neg), "No hay suficientes negativos en train_full para estos folds"

cv_splits = []
start_pos = 0
start_neg = 0
n_total = len(y_train)
all_indices = np.arange(n_total)

for i in range(n_splits):
    val_pos_idx = idx_pos[start_pos:start_pos + n_val_pos]
    val_neg_idx = idx_neg[start_neg:start_neg + n_val_neg]

    val_idx = np.concatenate([val_pos_idx, val_neg_idx])
    train_idx = np.setdiff1d(all_indices, val_idx)

    cv_splits.append((train_idx, val_idx))

    start_pos += n_val_pos
    start_neg += n_val_neg

print(f"Generados {len(cv_splits)} folds de CV con distribución similar al test.")

Validación por fold: 90 relevantes, 528 no relevantes (total 618)
Generados 5 folds de CV con distribución similar al test.

In [8]:
grid = GridSearchCV(
    estimator=pipe_svm,
    param_grid=param_grid,
    scoring=f1_relevant_scorer,
    cv=cv_splits,
    n_jobs=-1,
    verbose=1
)

print("🔎 Buscando mejores hiperparámetros (CV con distribución tipo test)...")
grid.fit(X_train, y_train)

print("\n============ MEJORES HIPERPARÁMETROS (CV tipo test) ============")
print(grid.best_params_)
print(f"Mejor F1 en CV (clase relevante): {grid.best_score_:.5f}")

# --- Evaluación en el test real ---
best_svm = grid.best_estimator_
y_pred = best_svm.predict(X_test)

print("\n============ RESULTADOS EN TEST ============")
print(classification_report(
    y_test,
    y_pred,
    digits=4,
    target_names=["No relevante", "Relevante"]
))

f1_minor = f1_score(y_test, y_pred, pos_label=1)
macro_f1 = f1_score(y_test, y_pred, average="macro")
accuracy = accuracy_score(y_test, y_pred)

print(f"\n🎯 F1 clase relevante (principal): {f1_minor:.4f}")
print(f"📈 Macro F1: {macro_f1:.4f}, Accuracy: {accuracy:.4f}")

🔎 Buscando mejores hiperparámetros (CV con distribución tipo test)...
Fitting 5 folds for each of 64 candidates, totalling 320 fits

============ MEJORES HIPERPARÁMETROS (CV tipo test) ============
{'svm__C': 1.0, 'svm__class_weight': None, 'tfidf__max_df': 0.9, 'tfidf__min_df': 1, 'tfidf__ngram_range': (1, 2)}
Mejor F1 en CV (clase relevante): 0.61552

============ RESULTADOS EN TEST ============
              precision    recall  f1-score   support

No relevante     0.9511    0.8106    0.8753       528
   Relevante     0.4048    0.7556    0.5271        90

    accuracy                         0.8026       618
   macro avg     0.6779    0.7831    0.7012       618
weighted avg     0.8715    0.8026    0.8246       618


🎯 F1 clase relevante (principal): 0.5271
📈 Macro F1: 0.7012, Accuracy: 0.8026

In [9]:
best_svm = grid.best_estimator_

y_pred = best_svm.predict(X_test)

print("\n============ RESULTADOS EN TEST ============")
print(classification_report(y_test, y_pred, digits=4))

f1_rel = f1_score(y_test, y_pred, pos_label=1)
macro = f1_score(y_test, y_pred, average="macro")
acc = (y_pred == y_test).mean()

print("\n>>> MÉTRICAS RESUMIDAS:")
print(f"F1 (Relevante): {f1_rel:.4f}")
print(f"Accuracy:        {acc:.4f}")
print(f"Macro F1:        {macro:.4f}")

============ RESULTADOS EN TEST ============
              precision    recall  f1-score   support

           0     0.9511    0.8106    0.8753       528
           1     0.4048    0.7556    0.5271        90

    accuracy                         0.8026       618
   macro avg     0.6779    0.7831    0.7012       618
weighted avg     0.8715    0.8026    0.8246       618


>>> MÉTRICAS RESUMIDAS:
F1 (Relevante): 0.5271
Accuracy:        0.8026
Macro F1:        0.7012

In [10]:
result_df = pd.DataFrame([{
    "Modelo": "SVM (Hiperparámetros óptimos)",
    "F1 (Relevante)": round(f1_rel, 4),
    "Accuracy": round(acc, 4),
    "Macro F1": round(macro, 4)
}])

result_df

                          Modelo  F1 (Relevante)  Accuracy  Macro F1
0  SVM (Hiperparámetros óptimos)          0.5271    0.8026    0.7012