#CARGA DE DATOS

In [1]:
!pip install -q transformers datasets evaluate torch accelerate
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
import pandas as pd
import numpy as np
import torch


from huggingface_hub import login
login(token="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")


dataset_name = "hugobecerra/DATASET3.0"
splits = {
    "train": f"hf://datasets/{dataset_name}/train.csv",
    "dev": f"hf://datasets/{dataset_name}/dev.csv",
    "test": f"hf://datasets/{dataset_name}/test_1.csv"
}

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.9 MB/s eta 0:00:00

In [2]:
def load_split(path, name):
    ds = load_dataset("csv", data_files={name: path}, delimiter="\t")[name]
    df = pd.DataFrame(ds)
    df.dropna(subset=["text", "label"], inplace=True)
    df["text"] = df["text"].astype(str)
    df["label"] = df["label"].astype(int)
    return df

train_df = pd.concat([
    load_split(splits["train"], "train"),
    load_split(splits["dev"], "dev")
], ignore_index=True)
test_df = load_split(splits["test"], "test")

print(f"TRAIN+DEV: {len(train_df)} frases ({train_df['label'].sum()} relevantes)")
print(f"TEST: {len(test_df)} frases ({test_df['label'].sum()} relevantes)")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

train.csv:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

dev.csv:   0%|          | 0.00/231k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

test_1.csv:   0%|          | 0.00/92.5k [00:00<?, ?B/s]

Generating test split: 0 examples [00:00, ? examples/s]

TRAIN+DEV: 10648 frases (2283 relevantes)
TEST: 618 frases (90 relevantes)

#Definición de modelos

In [3]:
model_names = {
    "BERT": "bert-base-uncased",
    "RoBERTa": "roberta-base",
    "DeBERTa": "microsoft/deberta-v3-base",
    "CTI-BERT": "ibm-research/CTI-BERT",
    "SecureBERT": "d4data/securebert-base",
    "SecBERT": "ahmedrachid/SEC-BERT"
}
results = []

In [4]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="binary")
    macro_f1 = precision_recall_fscore_support(labels, preds, average="macro")[2]
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "f1": f1, "macro_f1": macro_f1}

In [5]:
for name, checkpoint in model_names.items():
    print(f"\n🚀 Entrenando modelo: {name}")
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

    # Tokenización
    def tokenize(batch):
        return tokenizer(batch["text"], padding=True, truncation=True, max_length=128)
    train_ds = load_dataset("csv", data_files={"train": splits["train"]}, delimiter="\t")["train"].map(tokenize, batched=True)
    test_ds = load_dataset("csv", data_files={"test": splits["test"]}, delimiter="\t")["test"].map(tokenize, batched=True)

    args = TrainingArguments(
        output_dir=f"./results_{name}",
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        weight_decay=0.01,
        logging_dir="./logs",
        report_to="none"
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=test_ds,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    metrics = trainer.evaluate()
    results.append({"Modelo": name, "F1 (Relevante)": metrics["eval_f1"], "Accuracy": metrics["eval_accuracy"], "Macro F1": metrics["eval_macro_f1"]})

🚀 Entrenando modelo: BERT

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/9435 [00:00<?, ? examples/s]

Map:   0%|          | 0/618 [00:00<?, ? examples/s]

/tmp/ipython-input-2008711131.py:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Entrenando modelo: RoBERTa

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/9435 [00:00<?, ? examples/s]

Map:   0%|          | 0/618 [00:00<?, ? examples/s]

/tmp/ipython-input-2008711131.py:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Entrenando modelo: DeBERTa

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/371M [00:00<?, ?B/s]

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

model.safetensors:   0%|          | 0.00/371M [00:00<?, ?B/s]

Map:   0%|          | 0/9435 [00:00<?, ? examples/s]

Map:   0%|          | 0/618 [00:00<?, ? examples/s]

/tmp/ipython-input-2008711131.py:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

🚀 Entrenando modelo: CTI-BERT

OSError: malduwais/CTIBERT is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `hf auth login` or by passing `token=<your_token>`

In [6]:
df_results = pd.DataFrame(results).round(4)
display(df_results)

    Modelo  F1 (Relevante)  Accuracy  Macro F1
0     BERT          0.5099    0.7605    0.6757
1  RoBERTa          0.5323    0.8123    0.7074
2  DeBERTa          0.5193    0.7783    0.6876

In [7]:
model_names = {
    "CTI-BERT": "ibm-research/CTI-BERT",
    "SecureBERT": "cisco-ai/SecureBERT2.0-base",
    "SecBERT": "nlpaueb/sec-bert-base"
}
results = []

In [8]:
for name, checkpoint in model_names.items():
    print(f"\n🚀 Entrenando modelo: {name}")
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

    # Tokenización
    def tokenize(batch):
        return tokenizer(batch["text"], padding=True, truncation=True, max_length=128)
    train_ds = load_dataset("csv", data_files={"train": splits["train"]}, delimiter="\t")["train"].map(tokenize, batched=True)
    test_ds = load_dataset("csv", data_files={"test": splits["test"]}, delimiter="\t")["test"].map(tokenize, batched=True)

    args = TrainingArguments(
        output_dir=f"./results_{name}",
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        weight_decay=0.01,
        logging_dir="./logs",
        report_to="none"
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=test_ds,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    metrics = trainer.evaluate()
    results.append({"Modelo": name, "F1 (Relevante)": metrics["eval_f1"], "Accuracy": metrics["eval_accuracy"], "Macro F1": metrics["eval_macro_f1"]})

🚀 Entrenando modelo: CTI-BERT

tokenizer_config.json:   0%|          | 0.00/342 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/589 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at ibm-research/CTI-BERT and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/9435 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

Map:   0%|          | 0/618 [00:00<?, ? examples/s]

/tmp/ipython-input-2008711131.py:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🚀 Entrenando modelo: SecureBERT

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/599M [00:00<?, ?B/s]

Some weights of ModernBertForSequenceClassification were not initialized from the model checkpoint at cisco-ai/SecureBERT2.0-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/9435 [00:00<?, ? examples/s]

Map:   0%|          | 0/618 [00:00<?, ? examples/s]

/tmp/ipython-input-2008711131.py:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.
W1116 11:43:29.883000 736 torch/_inductor/utils.py:1436] [1/0_1] Not enough SMs to use max_autotune_gemm mode

🚀 Entrenando modelo: SecBERT

tokenizer_config.json:   0%|          | 0.00/263 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/568 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/439M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at nlpaueb/sec-bert-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/9435 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/439M [00:00<?, ?B/s]

Map:   0%|          | 0/618 [00:00<?, ? examples/s]

/tmp/ipython-input-2008711131.py:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

RuntimeError: [enforce fail at inline_container.cc:664] . unexpected pos 602788096 vs 602787988

In [9]:
df_results = pd.DataFrame(results).round(4)
display(df_results)

       Modelo  F1 (Relevante)  Accuracy  Macro F1
0    CTI-BERT          0.5419    0.7702    0.6943
1  SecureBERT          0.5512    0.8155    0.7175